//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvAndPortfolio.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLABOUT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLABOUT()
        {
            this.TBLCONTACTs = new HashSet<TBLCONTACT>();
        }
    
        public byte ID { get; set; }
        public string NAMESURNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string TITLE { get; set; }
        public string SUBTITLE { get; set; }
        public string ADDRESS { get; set; }
        public string MOBILE { get; set; }
        public Nullable<bool> RELOCATION { get; set; }
        public string AGE { get; set; }
        public string DEGREE { get; set; }
        public string EMAIL { get; set; }
        public string SUBDESCRIPTION { get; set; }
        public string PICURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCONTACT> TBLCONTACTs { get; set; }
    }
}
