//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvAndPortfolio.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCERTIFICATE
    {
        public byte ID { get; set; }
        public string TITLE { get; set; }
        public string DATE { get; set; }
        public string LOCATION { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
