//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvAndPortfolio.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSKILL
    {
        public byte ID { get; set; }
        public Nullable<byte> C_ { get; set; }
        public Nullable<byte> SQL { get; set; }
        public Nullable<byte> MVC5 { get; set; }
        public Nullable<byte> AZURE { get; set; }
        public Nullable<byte> PHOTOSHOP { get; set; }
        public Nullable<byte> SKETCHUP { get; set; }
    }
}
