//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvAndPortfolio.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTUDY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLSTUDY()
        {
            this.TBLSTUDYPICs = new HashSet<TBLSTUDYPIC>();
        }
    
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public string PICTURL { get; set; }
        public Nullable<byte> CATEGORY { get; set; }
    
        public virtual TBLCATEGORY TBLCATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTUDYPIC> TBLSTUDYPICs { get; set; }
    }
}
